language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'

before_script: cd shout-web
script: "mvn package"

notifications:
  email:
    recipients:
      - shout1233@gmail.com
